# GitHub Context

name: contexts texting
on:
  push:
  workflow_dispatch: 
  

jobs:
  dump_context_to_log:
    runs-on: ubuntu-latest
    steps:
    - name: dump github contexts
      env: 
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: echo "$GITHUB_CONTEXT"
      
    - name: dump job contexts
      env: 
        JOB_CONTEXT: ${{ toJson(job) }}
      run: echo "$JOB_CONTEXT"

    - name: dump ruuner contexts
      env: 
        RUNNER_CONTEXT: ${{ toJson(runner) }}
      run: echo "$RUNNER_CONTEXT"

    - name: dump secret contexts
      env: 
        SECRET_CONTEXT: ${{ toJson(secrets) }}
      run: echo "$SECRET_CONTEXT"
