name: generate ascii 

on:
  - push

jobs:
  ascii_job:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v4
      
      - name: install cowsay program
        run: sudo apt-get install cowsay -y

      - name: execute cowsay cmd
        run: cowsay -f dragon "Run for coverm I am a DRAGON....RAWR" >> dragon.txt

      - name: test file exists
        run: grep -i "dragon" dragon.txt

      - name: read file
        run: cat dragon.txt

      - name: list repo files
        run: ls -ltra
