name: matrix strategy 
on:
  push:
  workflow_dispatch: 

jobs:
  deploy:
    strategy:
      matrix:
        os: [ubuntu-latest, ubuntu-24.04, windows-latest]
        images: [hello-world, nginx]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Docker details
      run: docker info

    - name: Run Image
      run: docker run ${{ matrix.images }}