name: Multi Env actions
on:
  workflow_dispatch:
    inputs:
      choice:
        type: choice
        description: select the environment
        options:
        - dev
        - test
        - stage
        - prod

jobs:
  dev-job:
    if: ${{ inputs.choice == 'dev' }}
    runs-on: ubuntu-latest
    steps:
      - name: Print Hello World
        run: echo "Hello World" 
