name: multiple job workflow
on: push
jobs:
  build_job_1:
    runs-on: ubuntu-latest
    steps:
    - name: checkout repo
      uses: actions/checkout@v4
    
    - name: install cowsay
      run: sudo apt-get install cowsay -y

    - name: build cowsay file
      run: cowsay -f dragon "Run for coverm I am a DRAGON....RAWR" >> dragon.txt 

    - name: upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: dragon-text-file
        path: dragon.txt
        
  test_job_2:
    needs: build_job_1
    runs-on: ubuntu-latest
    steps:
    - name: download arcticat
      uses: actions/download-artifact@v3
      with:
        name: dragon-text-file

    - name: testing cowsay file
      run: grep -i "dragon" dragon.txt

  deploy_job_3:
    needs: [build_job_1, test_job_2]
    runs-on: ubuntu-latest
    steps: 
    - name: download arcticat
      uses: actions/download-artifact@v3
      with:
        name: dragon-text-file

    - name: read file
      run: cat dragon.txt