name: Multi Env actions
on:
  push:
    branches:
    - main
    - feature/dev
    - integration/test
  workflow_dispatch:
    inputs:
      choice:
        type: choice
        description: select the environment
        options:
        - dev
        - test
        - stage
        - prod

jobs:
  dev-job:
    if: ${{ inputs.choice == 'dev' }} || contains(github.ref,'main')
    runs-on: ubuntu-latest
    steps:
      - name: Print Hello World
        run: echo "Hello World" 
