# There are multiple events on which we can trigger workflow like on push, on pull request, manual etc.

name: exploring varibales and secrets
on:
  workflow_dispatch:

env:
  DOCKER_REGISTRY: docker.io
  DOCKER_IMAGE: nginx

jobs:
  docker_build_job:
    env: 
      DOCKER_USERNAME: shidhart1
    runs-on: ubuntu-latest
    steps:
    - name: build docker image
      run: echo docker build -t ${{ env.DOCKER_REGISTRY }}/$DOCKER_USERNAME/$DOCKER_IMAGE:latest

    - name: docker login
      env: 
        DOCKER_PASSWORD: s3userPass@d
      run: echo docker login --username=${{ env.DOCKER_USERNAME }} --password=$DOCKER_PASSWORD

    - name: docker push image
      run: echo docker push $DOCKER_REGISTRT/$DOCKER_USERNAME/${{ env.DOCKER_IMAGE }}:latest
