# Note: environment variables can be defined at workflow level or job level or step level.

name: exploring varibales and secrets
on: push

# jobs:
#   docker_build_job:
#     runs-on: ubuntu latest
#     steps:
#     - name: build docker image
#       run: echo docker build -t docker.io/username/imagename:latest

#     - name: docker login
#       run: echo docker login --username=shidhart1 --password=s3userPass@d 

#     - name: docker push image
#       run: echo docker push docker.io/username/imagename:latest

#   docker_deploy_job:
#     runs-on: ubuntu latest
#     steps:
#     - name: docker deploy
#       run: echo docker run -it -p 8080:80 docker.io/username/imagename:latest

env:
    DOCKER_REGISTRY: docker.io
    DOCKER_IMAGE: nginx
jobs:
  docker_build_job:
    env: 
      DOCKER_USERNAME: shidhart1
    runs-on: ubuntu-latest
    steps:
    - name: build docker image
      run: echo docker build -t {{ env.DOCKER_REGISTRY }}/$DOCKER_USERNAME/$DOCKER_IMAGE:latest

    - name: docker login
      env: 
        DOCKER_PASSWORD: s3userPass@d
      run: echo docker login --username=$DOCKER_USERNAME --password=$DOCKER_PASSWORD

    - name: docker push image
      run: echo docker push $DOCKER_REGISTRT/$DOCKER_USERNAME/$DOCKER_IMAGE:latest

  docker_deploy_job:
    env: 
      DOCKER_USERNAME: shidhart1
    runs-on: ubuntu-latest
    steps:
    - name: docker deploy
      run: echo docker run -it -p 8080:80 $DOCKER_REGISTRT/{{ env.DOCKER_USERNAME }}/$DOCKER_IMAGE:latest