# Note: environment variables can be defined at workflow level or job level or step level.

name: exploring varibales and secrets
on: push

jobs:
  docker_build_job:
    runs-on: ubuntu latest
    steps:
    - name: build docker image
      run: echo docker build -t docker.io/username/imagename:latest

    - name: docker login
      run: echo docker login --username=shidhart1 --password=s3userPass@d 

    - name: docker push image
      run: echo docker push docker.io/username/imagename:latest

  docker_deploy_job:
    runs-on: ubuntu latest
    steps:
    - name: docker deploy
      run: echo docker run -it -p 8080:80 docker.io/username/imagename:latest